name: Checks if the current version's tag has been released

on:
  workflow_call:
    outputs:
      version:
        description: "The version number of the release"
        value: ${{ jobs.check_version.outputs.version }}
      should_run:
        description: "Whether other jobs should run or not (false or empty)"
        value: ${{ jobs.check_version.outputs.should_run }}

jobs:
  check_version:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      version: ${{ steps.check_version.outputs.version }}
      should_run: ${{ steps.check_version.outputs.should_run }}
    steps:
      - name: Fetch top level files (including VERSION)
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            VERSION
          sparse-checkout-cone-mode: false
      - id: check_version
        continue-on-error: true
        name: Check if latest commit version is tagged
        run: |
          echo "version=$(cat VERSION)" >> "$GITHUB_OUTPUT"
          if git ls-remote --tags --exit-code -q origin "refs/tags/$(cat VERSION)"; then
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          fi
