name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'v0.1.6'

jobs:
  manual-release:
    name: Create PR
    runs-on: runs-on,runner=2cpu-linux-x64,ssh=false
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 845235 # LOK WASM App Id
          private-key: ${{ secrets.LOK_WASM_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: 'app-monorepo'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: coparse-inc/app-monorepo
          ref: dev

      - name: Git LFS
        run: |
          git config lfs.fetchinclude "*.wasm,*.patch"
          git lfs install
          git lfs pull

      - name: Restore artifacts for PR
        uses: runs-on/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: packages/lok
          key: release-${{ github.event.inputs.version }}

      - name: Restore artifacts for PR
        uses: runs-on/cache/restore@v4
        with:
          fail-on-cache-miss: false
          path: packages/editor/src/lok
          key: release-${{ github.event.inputs.version }}

      - name: Setup Git
        run: |
          git config user.name "lok-wasm[bot]"
          git config user.email "161704559+lok-wasm[bot]@users.noreply.github.com"

      - name: Check for existing PR
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          PR_NUMBER=$(gh pr list --head update/lok --base dev --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            echo "PR_EXISTS=true" >> $GITHUB_OUTPUT
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "PR_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Update branch and push
        env:
          PR_EXISTS: ${{ steps.check_pr.outputs.PR_EXISTS }}
        run: |
          [ -e packages/editor/src/lok ] && cp -rf packages/editor/src/lok/* packages/lok/
          # Apply a patch to revert the package loading changes
          cat << EOF | patch -p1
          diff --git a/packages/lok/soffice.mjs b/packages/lok/soffice.mjs
          index e66092af1..55b6536e9 100644
          --- a/packages/lok/soffice.mjs
          +++ b/packages/lok/soffice.mjs
          @@ -918,12 +918,11 @@ if (Module.withFcCache) {
                  PACKAGE_PATH = encodeURIComponent(location.pathname.toString().substring(0, location.pathname.toString().lastIndexOf("/")) + "/");
                }
                var PACKAGE_NAME = "soffice_fccache.data";
          -      var REMOTE_PACKAGE_BASE = "soffice_fccache.data";
                if (typeof Module["locateFilePackage"] === "function" && !Module["locateFile"]) {
                  Module["locateFile"] = Module["locateFilePackage"];
                  err("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)");
                }
          -      var REMOTE_PACKAGE_NAME = Module["locateFile"] ? Module["locateFile"](REMOTE_PACKAGE_BASE, "") : REMOTE_PACKAGE_BASE;
          +      var REMOTE_PACKAGE_NAME = new URL("./soffice_fccache.data", import.meta.url).href;
                var REMOTE_PACKAGE_SIZE = metadata["remote_package_size"];
                function fetchRemotePackage(packageName, packageSize, callback, errback) {
                  if (typeof process === "object" && typeof process.versions === "object" && typeof process.versions.node === "string") {
          @@ -1068,7 +1067,7 @@ if (Module.withFcCache) {
              };
              function runMetaWithFS() {
                Module["addRunDependency"]("soffice_fccache.data.js.metadata");
          -      var REMOTE_METADATA_NAME = Module["locateFile"] ? Module["locateFile"]("soffice_fccache.data.js.metadata", "") : "soffice_fccache.data.js.metadata";
          +      var REMOTE_METADATA_NAME = new URL("./soffice_fccache.data.js.metadata", import.meta.url).href;
                var xhr = new XMLHttpRequest;
                xhr.onreadystatechange = function() {
                  if (xhr.readyState === 4 && xhr.status === 200) {

          EOF

          if [ "$PR_EXISTS" = "true" ]; then
            git checkout update/lok
            git reset --soft origin/dev
            git add packages/lok
            git commit --amend -m "Update LOK WASM to ${{ github.event.inputs.version }}"
            git push -f origin update/lok
          else
            git checkout -b update/lok
            git add packages/lok
            git commit -m "Update LOK WASM to ${{ github.event.inputs.version }}"
            git push -f origin update/lok
          fi

      - name: Create or update PR
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_EXISTS: ${{ steps.check_pr.outputs.PR_EXISTS }}
          PR_NUMBER: ${{ steps.check_pr.outputs.PR_NUMBER }}
        run: |
          if [ "$PR_EXISTS" = "true" ]; then
            gh pr edit $PR_NUMBER \
              --title "Update LOK WASM to ${{ github.event.inputs.version }}" \
              --body "This is an automated PR created from the [\`lok-wasm\`](https://github.com/coparse-inc/lok-wasm) repository" \
              --add-label "lok-wasm" \
              --add-assignee "chase" \
              --add-reviewer "chase,synoet,whutchinson98,danielkweon"
            echo "Pull request updated: https://github.com/${{ github.repository }}/pull/$PR_NUMBER"
          else
            PR_URL=$(gh pr create --base dev --head ${{ github.repository_owner }}:update/lok \
              --title "Update LOK WASM to ${{ github.event.inputs.version }}" \
              --body "This is an automated PR created from the [\`lok-wasm\`](https://github.com/coparse-inc/lok-wasm) repository" \
              --label "lok-wasm" \
              --assignee "chase" \
              --reviewer "chase,synoet,whutchinson98,danielkweon")
            echo "Pull request created: $PR_URL"
          fi
